services:
  - type: cron
    name: market-comps-carscom-scraper
    env: python
    plan: starter
    schedule: "0 9 * * *"
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python scrape_market_comps.py

  - type: cron
    name: market-comps-cargurus-scraper
    env: python
    plan: starter
    schedule: "30 9 * * *"
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python scrape_cargurus.py

  - type: cron
    name: market-comps-autotrader-scraper
    env: python
    plan: starter
    schedule: "0 10 * * *"
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python scrape_autotrader.py

  - type: cron
    name: market-comps-cargurus-playwright
    env: python
    plan: starter
    schedule: "0 8 * * *"
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python scrape_cargurus_playwright.py
