services:
  - type: cron
    name: market-comps-carscom-scraper
    env: python
    plan: starter
    schedule: "0 9 * * *"  # Daily at 9am UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python scrape_market_comps.py

  - type: cron
    name: market-comps-cargurus-scraper
    env: python
    plan: starter
    schedule: "30 9 * * *"  # Daily at 9:30am UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python scrape_cargurus.py

  - type: cron
    name: market-comps-autotrader-scraper
    env: python
    plan: starter
    schedule: "0 10 * * *"  # Daily at 10am UTC (staggered 30 min after Cargurus)
    buildCommand: pip install -r requirements.txt
    startCommand: python scrape_autotrader.py
