services:
  - type: cron
    name: market-comps-carscom-scraper
    env: python
    plan: starter
    schedule: "0 9 * * *"         # Every day at 9am UTC. Change as needed.
    buildCommand: pip install -r requirements.txt
    startCommand: python scrape_market_comps.py
