services:
  - type: cron
    name: market-comps-carscom-scraper
    env: python
    plan: starter
    schedule: "0 9 * * *"  # Daily at 9am UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python competitor-scraper/scrape_market_comps.py

  - type: cron
    name: market-comps-cargurus-scraper
    env: python
    plan: starter
    schedule: "30 9 * * *"  # Daily at 9:30am UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python competitor-scraper/scrape_cargurus_market_comps.py
